# Generated by Django 2.0.3 on 2018-04-04 09:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakejieblog', '0002_auto_20180404_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='add_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间'),
        ),
    ]
