# Generated by Django 2.0.3 on 2018-04-04 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakejieblog', '0003_tag_add_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date_time'], 'verbose_name': '文章列表', 'verbose_name_plural': '文章列表'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['create_time'], 'verbose_name': '文章评论', 'verbose_name_plural': '文章评论'},
        ),
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['add_time'], 'verbose_name': '文章标签', 'verbose_name_plural': '文章标签'},
        ),
        migrations.AddField(
            model_name='category',
            name='url',
            field=models.CharField(default='', max_length=30, verbose_name='分配链接'),
        ),
        migrations.AddField(
            model_name='tag',
            name='url',
            field=models.CharField(default='', max_length=30, verbose_name='分配链接'),
        ),
    ]
