# Generated by Django 2.0.3 on 2018-04-04 14:13

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jakejieblog', '0004_auto_20180404_1127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=DjangoUeditor.models.UEditorField(default='', verbose_name='文章正文'),
        ),
    ]
