# Generated by Django 2.0.3 on 2018-04-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jakejieblog', '0006_auto_20180404_1438'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='tag',
        ),
        migrations.AddField(
            model_name='article',
            name='tag',
            field=models.ManyToManyField(to='jakejieblog.Tag', verbose_name='标签'),
        ),
    ]
