"""
Django settings for DJBlog project.

Generated by 'django-admin startproject' using Django 2.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""

import os
import sys

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, os.path.join(BASE_DIR, 'extract_apps'))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '$@%!%nj!45rbbk=x-*m$#m9&i2kal=17li%=eb8*=2afm-#bjx'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["127.0.0.1", 'www.jakejie.com']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'jakejieblog',
    # 使用xadmin后台管理框架替换掉admin
    'xadmin',
    'crispy_forms',
    'reversion',
    # 富文本编辑
    'DjangoUeditor',
    # 分页
    'pure_pagination',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'DJBlog.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                # 添加图片处理器
                'django.template.context_processors.media',
                'extract_apps.globle_varible.sidebar',
            ],
        },
    },
]

WSGI_APPLICATION = 'DJBlog.wsgi.application'

# Database
# https://docs.djangoproject.com/en/2.0/ref/settings/#databases

DATABASES = {
    'default': {
        # 'ENGINE': 'django.db.backends.sqlite3',
        # 'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        "ENGINE": "django.db.backends.mysql",
        "NAME": "jakejieblog",
        "HOST": "127.0.0.1",
        "PORT": 3306,
        # "USER": "jakejieblog",
        "USER": "root",
        # "PASSWORD": "jakejieblogpassword",
        "PASSWORD": "root",
        # "PASSWORD": "root",
    }
}

# Password validation
# https://docs.djangoproject.com/en/2.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/2.0/topics/i18n/

# LANGUAGE_CODE = 'en-us'
LANGUAGE_CODE = 'zh-hans'

# TIME_ZONE = 'UTC'
TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

# USE_TZ = True
# 数据库存储使用时间，True时间会被存为UTC的时间
USE_TZ = False

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.0/howto/static-files/

STATIC_URL = '/static/'
if DEBUG:
    STATIC_ROOT = os.path.join(BASE_DIR, 'static')
if not DEBUG:
    STATICFILES_DIRS = (
        os.path.join(BASE_DIR, "static"),
    )

# 设置我们上传文件的路径
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# 发送邮件配置
EMAIL_HOST = "smtp.163.com"
EMAIL_PORT = 25
EMAIL_HOST_USER = "jakejie@163.com"
EMAIL_HOST_PASSWORD = "zhujie165102"
EMAIL_USE_TLS = False
EMAIL_FROM = "jakejie@163.com"

# 此处重载是为了使我们的UserProfile生效
AUTH_USER_MODEL = "jakejieblog.UserProfile"

# 设置邮箱和用户名均可登录
AUTHENTICATION_BACKENDS = (
    'jakejieblog.views.CustomBackend',
)
# 分页的设置
PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 10,  # 是总共会显示多少个page。(包括省略号，包括两边和中间)
    'MARGIN_PAGES_DISPLAYED': 2,  # 是旁边会显示多少个。
    'SHOW_FIRST_PAGE_WHEN_INVALID': True,  # 当输入页数不合法是否要跳到第一页
}
# 每页显示多少数据
PAGE_SETTING = 2
